### ISSUE TITLE
incompatible with ff 62

### ISSUE THREAD

**Issue by vincitored** [fligtar/password-exporter#107]
do you plan to implement it for ff 62?

**Comment by jvillalobos** [comment]
Due to missing password APIs, it's not possible at the moment. Once those are implemented, we will try to port this add-on so it continues to work. See #80

**Comment by KB-Concepts** [comment]
Wow so cool of you to get back to me!  :-)
Are you the developer or is Justin?

**Comment by KB-Concepts** [comment]
Password-Exporter
I just want you to know this Add-on for FireFox is by far the best one anywhere on the planet!  I love it so much that I’ve stayed with FireFox v56.x just because yours is the only one that saves passwords and allows importing and exporting with out any problems. 
I know it is an old Add-on, but it still works with the older version of FireFox.  Is there any chance of making this work in the newest version of FireFox, Chrome or any other Browser?  I’m looking forward to hearing from you.
Sent to Justin also.  :-)

**Comment by KB-Concepts** [comment]
Since v1.3 is incompatible, is there any other Add-on, Extension or App that works as easy ans as good as this one?
